package com.company.jaxws.handler.cardservice.common;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2018-12-25T15:20:25.790+03:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://cardservice.handler.jaxws.company.com/service", name = "CardServicePortType")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CardServicePortType {

    @WebMethod(action = "tns:authorizePayment")
    @WebResult(name = "AuthorizationStatus", targetNamespace = "http://cardservice.handler.jaxws.company.com/creditcard", partName = "result")
    public AuthorizationStatus authorizePayment(
        @WebParam(partName = "parameters", name = "AuthorizationRequest", targetNamespace = "http://cardservice.handler.jaxws.company.com/creditcard")
        AuthorizationRequest parameters
    ) throws CardServiceException;
}
