
package com.company.jaxws.handler.cardservice.common;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.7
 * 2018-12-25T15:20:25.727+03:00
 * Generated source version: 3.2.7
 */

@WebFault(name = "FaultInfo", targetNamespace = "http://cardservice.handler.jaxws.company.com/exception")
public class CardServiceException extends Exception {

    private com.company.jaxws.handler.cardservice.common.FaultInfo faultInfo;

    public CardServiceException() {
        super();
    }

    public CardServiceException(String message) {
        super(message);
    }

    public CardServiceException(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public CardServiceException(String message, com.company.jaxws.handler.cardservice.common.FaultInfo faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    public CardServiceException(String message, com.company.jaxws.handler.cardservice.common.FaultInfo faultInfo, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    public com.company.jaxws.handler.cardservice.common.FaultInfo getFaultInfo() {
        return this.faultInfo;
    }
}
