
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.company.jaxws.handler.cardservice.common;

import org.apache.log4j.Logger;
import javax.jws.*;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2018-12-25T15:20:25.763+03:00
 * Generated source version: 3.2.7
 *
 */

@javax.jws.WebService(
                      serviceName = "CardService",
                      portName = "CardServicePort",
                      targetNamespace = "http://cardservice.handler.jaxws.company.com/service",
                      //wsdlLocation = "file:src/main/webapp/WEB-INF/wsdl/CreditCardService.wsdl",
                      endpointInterface = "com.company.jaxws.handler.cardservice.common.CardServicePortType")
@HandlerChain(name = "CreditCardChainHandler", file = "creditcardservicehandler.xml")

public class CardServicePortImpl implements CardServicePortType {

    private static final Logger LOG = Logger.getLogger(CardServicePortImpl.class);

    /* (non-Javadoc)
     * @see com.company.jaxws.handler.cardservice.common.CardServicePortType#authorizePayment(com.company.jaxws.handler.cardservice.common.AuthorizationRequest parameters)*
     */
    public com.company.jaxws.handler.cardservice.common.AuthorizationStatus authorizePayment(AuthorizationRequest parameters) throws CardServiceException   {

        LOG.info("Executing operation authorizePayment");
        LOG.debug("parameters = " + parameters.toString());

        System.out.println("Executing operation authorizePayment");
        System.out.println("parameters = " + parameters.toString());


        throw new CardServiceException("Принудительный Exception", new com.company.jaxws.handler.cardservice.common.FaultInfo());

        /*System.out.println(parameters);
        try {
            com.company.jaxws.handler.cardservice.common.AuthorizationStatus _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }*/
        //throw new CardServiceException("CardServiceException...");
    }

}
