
package com.company.jaxws.handler.cardservice.common;

import javax.xml.ws.Endpoint;
import org.apache.log4j.Logger;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2018-12-25T15:20:25.801+03:00
 * Generated source version: 3.2.7
 *
 */

public class CardServicePortType_CardServicePort_Server{
    private final Logger LOG = Logger.getLogger(CardServicePortType_CardServicePort_Server.class);

    protected CardServicePortType_CardServicePort_Server() throws CardServiceException {
        System.out.println("Starting Server");
        Object implementor = new CardServicePortImpl();
        String address = "http://localhost:8087/services/CreditCardService";


        Endpoint.publish(address, implementor);
    }

    public static void main(String args[]) throws CardServiceException {

        new CardServicePortType_CardServicePort_Server();

        try {
            System.out.println("Server ready...");

            Thread.sleep(5 * 60 * 1000);
            System.out.println("Server exiting");
            System.exit(0);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
    }
}
