
package com.StockExceptionTest;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.7
 * 2018-12-21T12:29:19.452+03:00
 * Generated source version: 3.2.7
 */

@WebFault(name = "InvalidSymbolFault", targetNamespace = "http://scatesttool.stockexceptiontestservice")
public class InvalidSymbolFault_Exception extends Exception {

    private com.StockExceptionTest.InvalidSymbolFault invalidSymbolFault;

    public InvalidSymbolFault_Exception() {
        super();
    }

    public InvalidSymbolFault_Exception(String message) {
        super(message);
    }

    public InvalidSymbolFault_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public InvalidSymbolFault_Exception(String message, com.StockExceptionTest.InvalidSymbolFault invalidSymbolFault) {
        super(message);
        this.invalidSymbolFault = invalidSymbolFault;
    }

    public InvalidSymbolFault_Exception(String message, com.StockExceptionTest.InvalidSymbolFault invalidSymbolFault, java.lang.Throwable cause) {
        super(message, cause);
        this.invalidSymbolFault = invalidSymbolFault;
    }

    public com.StockExceptionTest.InvalidSymbolFault getFaultInfo() {
        return this.invalidSymbolFault;
    }
}
