
package com.StockExceptionTest;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.7
 * 2018-12-21T12:29:19.484+03:00
 * Generated source version: 3.2.7
 */

@WebFault(name = "MarketClosedFault", targetNamespace = "http://scatesttool.stockexceptiontestservice")
public class MarketClosedFault_Exception extends Exception {

    private com.StockExceptionTest.MarketClosedFault marketClosedFault;

    public MarketClosedFault_Exception() {
        super();
    }

    public MarketClosedFault_Exception(String message) {
        super(message);
    }

    public MarketClosedFault_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public MarketClosedFault_Exception(String message, com.StockExceptionTest.MarketClosedFault marketClosedFault) {
        super(message);
        this.marketClosedFault = marketClosedFault;
    }

    public MarketClosedFault_Exception(String message, com.StockExceptionTest.MarketClosedFault marketClosedFault, java.lang.Throwable cause) {
        super(message, cause);
        this.marketClosedFault = marketClosedFault;
    }

    public com.StockExceptionTest.MarketClosedFault getFaultInfo() {
        return this.marketClosedFault;
    }
}
