package com.StockExceptionTest;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2018-12-21T12:29:19.515+03:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://scatesttool.stockexceptiontestservice", name = "StockExceptionTest")
@XmlSeeAlso({ObjectFactory.class})
public interface StockExceptionTest {

    @WebMethod
    @RequestWrapper(localName = "stockQuoteOffer", targetNamespace = "http://scatesttool.stockexceptiontestservice", className = "com.StockExceptionTest.StockQuoteOffer")
    @ResponseWrapper(localName = "stockQuoteOfferResponse", targetNamespace = "http://scatesttool.stockexceptiontestservice", className = "com.StockExceptionTest.StockQuoteOfferResponse")
    @WebResult(name = "stockQuoteOfferReturn", targetNamespace = "")
    public com.StockExceptionTest.StockOffer stockQuoteOffer(
        @WebParam(name = "input", targetNamespace = "")
        com.StockExceptionTest.StockOffer input
    ) throws InvalidSymbolFault_Exception, MarketClosedFault_Exception;
}
