package com.StockExceptionTest;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2018-12-21T12:29:19.531+03:00
 * Generated source version: 3.2.7
 *
 */
@WebServiceClient(name = "StockExceptionTestService",
                  wsdlLocation = "file:src/main/webapp/WEB-INF/wsdl/StockExceptionTest.wsdl",
                  targetNamespace = "http://scatesttool.stockexceptiontestservice")
public class StockExceptionTestService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://scatesttool.stockexceptiontestservice", "StockExceptionTestService");
    public final static QName StockExceptionTestServiceSoapPort = new QName("http://scatesttool.stockexceptiontestservice", "StockExceptionTestServiceSoapPort");
    static {
        URL url = null;
        try {
            url = new URL("file:src/main/webapp/WEB-INF/wsdl/StockExceptionTest.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(StockExceptionTestService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:src/main/webapp/WEB-INF/wsdl/StockExceptionTest.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public StockExceptionTestService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public StockExceptionTestService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StockExceptionTestService() {
        super(WSDL_LOCATION, SERVICE);
    }





    /**
     *
     * @return
     *     returns StockExceptionTest
     */
    @WebEndpoint(name = "StockExceptionTestServiceSoapPort")
    public StockExceptionTest getStockExceptionTestServiceSoapPort() {
        return super.getPort(StockExceptionTestServiceSoapPort, StockExceptionTest.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StockExceptionTest
     */
    @WebEndpoint(name = "StockExceptionTestServiceSoapPort")
    public StockExceptionTest getStockExceptionTestServiceSoapPort(WebServiceFeature... features) {
        return super.getPort(StockExceptionTestServiceSoapPort, StockExceptionTest.class, features);
    }

}
