
package com.kpbs.productionOrder;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2018-12-21T16:49:36.029+03:00
 * Generated source version: 3.2.7
 *
 */

public class ProductionOrderIn_ProductionOrderIn_Server{

    protected ProductionOrderIn_ProductionOrderIn_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new ProductionOrder_InImpl();
        String address = "http://localhost:8080/EGAISSevlet/services/ProductionOrder_In";
        Endpoint.publish(address, implementor);
    }

    public static void main(String args[]) throws java.lang.Exception {
        new ProductionOrderIn_ProductionOrderIn_Server();
        System.out.println("Server ready...");

        Thread.sleep(5 * 60 * 1000);
        System.out.println("Server exiting");
        System.exit(0);
    }
}
