
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.kpbs.productionOrder;

import java.util.logging.Logger;
import javax.annotation.Resource;
import javax.jws.*;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.namespace.QName;
import javax.xml.soap.SOAPConstants;
import javax.xml.soap.SOAPException;
import javax.xml.soap.SOAPFactory;
import javax.xml.soap.SOAPFault;
import javax.xml.ws.WebServiceContext;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.soap.SOAPFaultException;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2018-12-21T16:49:35.991+03:00
 * Generated source version: 3.2.7
 *
 */

@javax.jws.WebService(
                      serviceName = "ProductionOrder_InService",
                      portName = "ProductionOrder_In",
                      targetNamespace = "http://esb.z-t-z.ru/Integration/SAP",
                      wsdlLocation = "file:src/main/webapp/WEB-INF/wsdl/ProductionOrder_In.wsdl",
                      endpointInterface = "com.kpbs.productionOrder.ProductionOrderIn")
@HandlerChain(name = "ProductionOrderChainHandler", file = "productionorderhandler.xml")
public class ProductionOrder_InImpl implements ProductionOrderIn {

    @Resource
    WebServiceContext context;

    private static final Logger LOG = Logger.getLogger(ProductionOrder_InImpl.class.getName());

    /* (non-Javadoc)
     * @see com.kpbs.productionOrder.ProductionOrderIn#productionOrderIn(com.kpbs.productionOrder.ProductionOrder productionOrder)*
     */
    public void productionOrderIn(ProductionOrder productionOrder) throws ProductionOrderSaveException   {
        LOG.info("Executing operation productionOrderIn");
        System.out.println(productionOrder);
        /*try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }*/

        //context.getMessageContext()
        //throw new ProductionOrderSaveException("ProductionOrderSaveException...");
        //throw new WebServiceException("Unable to create ticket.");

        String faultString = "String Y";
        String faultCodeValue = "Code X";
        QName faultCode = new QName("nameSpaceURI", faultCodeValue);
        SOAPFault soapFault = null;

        try {
            soapFault = SOAPFactory.newInstance(SOAPConstants.SOAP_1_1_PROTOCOL).createFault(faultString, faultCode);
            throw new SOAPFaultException(soapFault);
        } catch (SOAPException e) {
            e.printStackTrace();
        }
        //throw new ProductionOrderSaveException("new ProductionOrderSaveException");
    }

}
