package com.kpbs.productionOrder;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2018-12-21T16:49:36.017+03:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://esb.z-t-z.ru/Integration/SAP", name = "ProductionOrder_In")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ProductionOrderIn {

    @WebMethod(operationName = "ProductionOrder_In", action = "http://sap.com/xi/WebService/soap1.1")
    @Oneway
    public void productionOrderIn(
        @WebParam(partName = "ProductionOrder", name = "ProductionOrder", targetNamespace = "http://esb.z-t-z.ru/Integration/SAP")
        ProductionOrder productionOrder
    ) throws ProductionOrderSaveException;
}
