
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.example.sample;

import com.sun.xml.messaging.saaj.soap.SOAPVersionMismatchException;

import org.apache.log4j.Logger;

import javax.jws.*;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.namespace.QName;
import javax.xml.soap.SOAPConstants;
import javax.xml.soap.SOAPException;
import javax.xml.soap.SOAPFactory;
import javax.xml.soap.SOAPFault;
import javax.xml.ws.BindingType;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import javax.xml.ws.soap.SOAPFaultException;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2018-12-20T14:48:59.669+03:00
 * Generated source version: 3.2.7
 */

@javax.jws.WebService(
        serviceName = "TestJaxWsService",
        portName = "testJaxWs",
        targetNamespace = "http://esb.z-t-z.ru/Integration/SAP",
        wsdlLocation = "file:src/main/webapp/WEB-INF/wsdl/input.wsdl",
        endpointInterface = "com.example.sample.TestJaxWs")
@HandlerChain(name = "ExamplesampleChainHandler", file = "serversoaphandler.xml")
@javax.jws.soap.SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public class TestJaxWsImpl implements TestJaxWs {

    private static final Logger LOG = Logger.getLogger(TestJaxWsImpl.class);

    /* (non-Javadoc)
     * @see com.example.sample.TestJaxWs#jaxWsTest1(java.lang.String information, int count)*
     */
    public java.lang.String jaxWsTest1(java.lang.String information, int count /* JaxWsTest1 jaxWsTest1*/) throws UserDefinedException {
        LOG.info("Executing operation jaxWsTest1");
        System.out.println(information);
        //System.out.println(jaxWsTest1.information);
        System.out.println(count);
        //System.out.println(jaxWsTest1.count);
        /*try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }*/
        //throw new UserDefinedException("UserDefinedException...");


        /*if (count == 11) {
            String faultString = "String Y";
            String faultCodeValue = "Code X";
            QName faultCode = new QName("nameSpaceURI", faultCodeValue);
            SOAPFault soapFault = null;

            try {
                soapFault = SOAPFactory.newInstance(SOAPConstants.SOAP_1_1_PROTOCOL).createFault(faultString, faultCode);
                LOG.debug("before throw SOAPFaultException");
                throw new SOAPFaultException(soapFault);
            } catch (SOAPException e) {
                e.printStackTrace();
            }
        }*/
        return information;
        //return jaxWsTest1.information;

    }
}