
package com.example.sample;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2018-12-20T14:48:59.700+03:00
 * Generated source version: 3.2.7
 *
 */

public class TestJaxWs_TestJaxWs_Server{

    protected TestJaxWs_TestJaxWs_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new TestJaxWsImpl();
        String address = "http://localhost:8087/services/TestJaxWs";
        Endpoint.publish(address, implementor);
    }

    public static void main(String args[]) throws java.lang.Exception {
        new TestJaxWs_TestJaxWs_Server();
        System.out.println("Server ready...");

        Thread.sleep(5 * 60 * 1000);
        System.out.println("Server exiting");
        System.exit(0);
    }
}
