package com.example.sample;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2018-12-20T14:48:59.685+03:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://esb.z-t-z.ru/Integration/SAP", name = "TestJaxWs")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.WRAPPED)
public interface TestJaxWs {

    @WebMethod
    @RequestWrapper(localName = "jaxWsTest1", targetNamespace = "http://esb.z-t-z.ru/Integration/SAP", className = "com.example.sample.JaxWsTest1")
    @ResponseWrapper(localName = "jaxWsTest1Response", targetNamespace = "http://esb.z-t-z.ru/Integration/SAP", className = "com.example.sample.JaxWsTest1Response")
    //@WebResult(name = "return", targetNamespace = "")
    public java.lang.String jaxWsTest1(
        @WebParam(name = "information", targetNamespace = "")
        java.lang.String information,
        @WebParam(name = "count", targetNamespace = "")
        int count
    ) throws UserDefinedException;
}
