
package com.example.sample;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.7
 * 2018-12-20T14:48:59.622+03:00
 * Generated source version: 3.2.7
 */

@WebFault(name = "UserDefinedFault", targetNamespace = "http://esb.z-t-z.ru/Integration/SAP")
public class UserDefinedException extends Exception {

    private com.example.sample.UserDefinedFault userDefinedFault;

    public UserDefinedException() {
        super();
    }

    public UserDefinedException(String message) {
        super(message);
    }

    public UserDefinedException(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public UserDefinedException(String message, com.example.sample.UserDefinedFault userDefinedFault) {
        super(message);
        this.userDefinedFault = userDefinedFault;
    }

    public UserDefinedException(String message, com.example.sample.UserDefinedFault userDefinedFault, java.lang.Throwable cause) {
        super(message, cause);
        this.userDefinedFault = userDefinedFault;
    }

    public com.example.sample.UserDefinedFault getFaultInfo() {
        return this.userDefinedFault;
    }
}
