
package com.helloworldcxf;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.7
 * 2018-12-28T13:20:25.907+03:00
 * Generated source version: 3.2.7
 */

@WebFault(name = "faultDetail", targetNamespace = "http://apache.org/hello_world_soap_http/types")
public class PingMeFault extends Exception {

    private com.helloworldcxf.FaultDetail faultDetail;

    public PingMeFault() {
        super();
    }

    public PingMeFault(String message) {
        super(message);
    }

    public PingMeFault(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public PingMeFault(String message, com.helloworldcxf.FaultDetail faultDetail) {
        super(message);
        this.faultDetail = faultDetail;
    }

    public PingMeFault(String message, com.helloworldcxf.FaultDetail faultDetail, java.lang.Throwable cause) {
        super(message, cause);
        this.faultDetail = faultDetail;
    }

    public com.helloworldcxf.FaultDetail getFaultInfo() {
        return this.faultDetail;
    }
}
