
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.helloworldcxf;

import java.util.logging.Logger;
import javax.jws.*;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2018-12-28T13:20:25.941+03:00
 * Generated source version: 3.2.7
 *
 */

@javax.jws.WebService(
                      serviceName = "SOAPService",
                      portName = "SoapPort",
                      targetNamespace = "http://apache.org/hello_world_soap_http",
                      wsdlLocation = "file:src/main/webapp/WEB-INF/wsdl/HelloWorldCXF.wsdl",
                      endpointInterface = "com.helloworldcxf.Greeter")
@HandlerChain(name = "GreetMeChainHandler", file = "greetmehandler.xml")
public class SoapPortImpl implements Greeter {

    private static final Logger LOG = Logger.getLogger(SoapPortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.helloworldcxf.Greeter#pingMe()*
     */
    public void pingMe() throws PingMeFault   {
        LOG.info("Executing operation pingMe");
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new PingMeFault("pingMeFault...");
    }

    /* (non-Javadoc)
     * @see com.helloworldcxf.Greeter#greetMe(java.lang.String requestType)*
     */
    public java.lang.String greetMe(java.lang.String requestType) throws PingMeFault {
        throw new PingMeFault("eee");
        /*LOG.info("Executing operation greetMe");
        System.out.println(requestType);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }*/
    }

    /* (non-Javadoc)
     * @see com.helloworldcxf.Greeter#greetMeOneWay(java.lang.String requestType)*
     */
    public void greetMeOneWay(java.lang.String requestType) {
        LOG.info("Executing operation greetMeOneWay");
        System.out.println(requestType);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.helloworldcxf.Greeter#sayHi()*
     */
    public java.lang.String sayHi() {
        LOG.info("Executing operation sayHi");
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
