
package com.helloworldcxf.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2018-12-28T14:37:12.180+03:00
 * Generated source version: 3.2.7
 *
 */
public final class Greeter_SoapPort_Client {

    private static final QName SERVICE_NAME = new QName("http://apache.org/hello_world_soap_http", "SOAPService");

    private Greeter_SoapPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        /*URL wsdlURL = SOAPService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }*/
        URL wsdlURL = new URL("file:C:\\projects\\Intergation1CModule\\FaultMessage\\src\\main\\webapp\\WEB-INF\\wsdl\\HelloWorldCXF.wsdl");


        SOAPService ss = new SOAPService(wsdlURL, SERVICE_NAME);
        Greeter port = new SoapPortImpl();
        port = ss.getSoapPort();

        {
        System.out.println("Invoking pingMe...");
        try {
            port.pingMe();

        } catch (PingMeFault e) {
            System.out.println("Expected exception: pingMeFault has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking greetMe...");
        java.lang.String greetMeStr = "";
        java.lang.String greetMeResponse = port.greetMe(greetMeStr);
        System.out.println("greetMe.result=" + greetMeResponse);
        }
        /*{
        System.out.println("Invoking greetMeOneWay...");
        java.lang.String _greetMeOneWay_requestType = "";
        port.greetMeOneWay(_greetMeOneWay_requestType);
        }
        {
        System.out.println("Invoking sayHi...");
        java.lang.String _sayHi__return = port.sayHi();
        System.out.println("sayHi.result=" + _sayHi__return);
        }*/

        System.exit(0);
    }

}
